### ISSUE TITLE
Covariance not invertible

### ISSUE THREAD

**Issue by h3ndrk** [HULKs/hulk#1039]
... a panic that occured during the test game on 2024-05-29

**Comment by knoellle** [comment]
@oleflb said this may be caused by the ball filter processing multiple messages from other robots within the same cycle.
Since they are processed with the same local control cycle timestamp, one of the filter updates has a time delta of 0.

**Comment by schmidma** [comment]
Two questions:
1. The ball filter does not process any messages from other robots?! The role assignment is processing network messages and composes the team ball. Which is subsequently processed by the `BallStateComposer`
2. how does a filter update depends on the time delta? There should be no problems in updating kalman filters multiple times in a single time frame. The time is only required when predicting the model.

**Comment by knoellle** [comment]
This was ultimately caused because a penalized player received a network message from a player detecting a referee pose in standby.
Before #1113, this used the same message we also use for striker assigment and both player's positions were faked to be in the center of the field.
Since we use received network messages in the obstacle filter which weighs the measurement noise of an update by the distance to the detection, the measurement noise was 0 which in turn lead to an uninvertible covariance matrix.
