### ISSUE TITLE
post-game task: investigate why our striker sometimes walks backwards away from the ball

### ISSUE THREAD

**Issue by Narcha** [HULKs/hulk#1332]
this happened at least twice in our game vs. B-Human today.
- golden goal, just before the goal was scored (i think), robot 40:7
- first half, after the 0-2 goal, 4:50 remaining, robot 38:3

It happened again in the game vs. RoboÉireann today (20.07.):
- right after the first kickoff in the first half, robot 34:4
- robot 39:6 at 8:20 remaining in the first half

**Comment by schmidma** [comment]
I checked both situations in the RoboEireann game:

in the first one the robot was positioning for the filtered ball having velocity and moving slightly towards the robot and then it was accelerating, but only slowly...

in the second one the supposed striker was not striker, but due to role assignment delay still striker supporter and therefore positioned in a supporting position.
