### ISSUE TITLE
Implement time to reach position function

### ISSUE THREAD

**Issue by Narcha** [HULKs/hulk#297]
what the title says.
Possible use cases:
- better striker role assignment decisions
- When unable to return to own half of the field in time after opponent scoring a goal, walk to center circle instead to prevent penalty

**Comment by PasGl** [comment]
Notes for striker role-assignment:

Striker-messages should contain a guesstimated time-to-reach shooting-pose which takes Path-planning and ball-movement projections into account (so it is punished for chasing behind a dribbling opponent etc).

That way other players can compare to their own time-to-reach ball guesstimate with the striker's, without having the same information about obstacles available.

All in all this topic is difficult and imperfections in the guesstimation can lead to shitty team-behavior easily.

**Comment by MaikRe** [comment]
Discussed steps that should be taken:

1. Implement a time to reach ball into the spl message (the one sent between teammates) which should replace the ball position and robot_to_field such that each robots time to reach ball is only proportional to its position relative to the ball, effectively not changing current behavior. In that regard:
1.1. Add mentioned above into spl message
1.2. modify role assignment to use this new information
2. Create node for time to reach ball/time to reach kick position, which may be dependent on many other factors and would therefore need to write into the persistent state.
2.1. Use kick decisions in all roles since striker is currently only one using them
2.2. Factor in path planning, i.e. walking straight lines is fast, turning around is slow
3. Look at what others (such as ball model) are doing. Rather than planning to current ball, plan to kick decision based on where ball will roll to. Ball rolling towards me -> Faster time to reach kick position
4. ....
5. Profit?

**Comment by Narcha** [comment]
Notes for implementors:
- Steps 1 + 2 cannot be done separately.
- todo:
  - In role assignment cycler: calculate calculate TTRKP based on own ball using path planning
  - in process_role_state_machine: use team ball to recalculate TTRKP and update desired role
