### ISSUE TITLE
Investigate kick-off side kick

### ISSUE THREAD

**Issue by Narcha** [HULKs/hulk#311]
During our game against R-ZWEI KICKERS, our striker decided twice to make the kick-off using a side kick.
This occurred after the 1:1 goal, and at the start of the second half.

**Comment by Narcha** [comment]
This happened again in a game yesterday.

**Comment by schmidma** [comment]
Can you remember which game it was?

**Comment by Narcha** [comment]
I *think* it was against Bembelbots, but I'm not sure.

**Comment by Narcha** [comment]
See [(1)](https://www.youtube.com/live/IOfPfSRgtHw?feature=share&t=26848) and [(2)](https://www.youtube.com/live/IOfPfSRgtHw?feature=share&t=30473).

**Comment by MaikRe** [comment]
This happened in our test game on 07.09.2024 again, notably now with #1101 merged, but still weird that it happened.

**Comment by knoellle** [comment]
The reason for that was that the kick off striker had the MidfielderLeft role for a moment and tried to walk into the opponent half.
While turning towards the target position it became striker and decided to kick. At that time, sidekick was the best kick to do.
![image](https://github.com/HULKs/hulk/assets/33729490/f94087d6-3324-437b-9635-3a197f93f3be)

**Comment by knoellle** [comment]
During Set, the kick off Striker doesn't see the ball because it's just too far outside the bottom image I guess. Apparently #1111 didn't help either.
At the transition to Play, this robot then becomes Loser for one cycle (having forcibly been striker during Set).
Another robot sees the ball and claims Striker, at which point our kick-off striker becomes Midfielder.
About two seconds after kick-off, the kick-off striker actually becomes striker and executes the kick-off.

![image](https://github.com/HULKs/hulk/assets/33729490/4159ba50-88c9-4f59-8039-5271dedc8c0f)

**Comment by schmidma** [comment]
I'm actually okay with the striker doing a side kick here. It was the correct action to do. The ball reached its position close to the supporter.

I'd be in favor of keeping it as is

**Comment by knoellle** [comment]
I agree, but the kick-off striker should be positioned such that it doesn't become loser when the game begins.
Separate issue though

**Comment by schmidma** [comment]
Briefly discussed with vivi and ole, we agree that this is an issue, but a separate one. Closing for now...
Superseded by #1130
