### ISSUE TITLE
Communication is not properly disabled by `pepsi pregame`

### ISSUE THREAD

**Issue by Narcha** [HULKs/hulk#343]
For some reason, `twix` sessions did not terminate when preparing for a game, and stayed connected during the game as well.

**Comment by h3ndrk** [comment]
We are currently disabling Communication via

https://github.com/HULKs/hulk/blob/48d852fc7cdcda020de30ecc695563b76ec711c8/crates/repository/src/lib.rs#L249-L266

but this is not respected anymore in Framework 2 and is now hardcoded to always be enabled, see here:

https://github.com/HULKs/hulk/blob/48d852fc7cdcda020de30ecc695563b76ec711c8/crates/hulk/src/bin/nao.rs#L29-L36

If we pass `Some(...)` to the run function, this will enable the Communication server. `None` will disable it.

I already started improving our parameters in https://github.com/HULKs/hulk/pull/86 but this is not ready for prime time and needs some further cleanup. Some things of this PR are not needed and can be stripped. In addition, it needs a rebase because it is quite old.

**Comment by knoellle** [comment]
Was fixed in #418.
I thought github would close it automatically when referenced as "fix #issuenumber" in a commit that is pushed to the default branch. 🤷🏻
