### ISSUE TITLE
Penalty shootout broken after one round

### ISSUE THREAD

**Issue by knoellle** [HULKs/hulk#345]
According to the Dutch Nao Team, penalty shootout works fine for one round (one defense, one offense) but devolves into chaos.
Robots seem to be incorrectly (un-)penalized, walking around, etc.

Investigate whether we can replicate this behavior, perhaps creating behavior simulator scenarios.

**Comment by Fyor** [comment]
We recently did some more testing and found it working far better! This was most likely due to a wrong Gamecontroller version being used during testing, which resulted in incorrectly penalized players, making the behavior weird and dependant on player number. 

There is still a problem where the keeper robot does the LookAround motion when going from set to playing. This also happens for the kicking player, but is less of a problem.

**Comment by MaikRe** [comment]
I created a pull request to fix this for both striker and keeper. Please feel free to comment if you think it should be kept for the striker.
