### ISSUE TITLE
More active HULKs on the field

### ISSUE THREAD

**Issue by Bendodroid** [HULKs/hulk#38]
We want to have more active HULKs on the field during a game. 
This means less falling over, less bumping into other robots, and a faster stand-up motion if a fall occurs. 
Less bumping into other robots will also help reducing our penalties.
For this to happen we need better obstacle detection (including the damned goal posts).
See also:  Robot Detection #44

This topic is closely related to 7v7 Games #37

**Comment by philipniklas-r** [comment]
Philip from the team B-Human here,

to the topic ``less falls`` and ``faster stand-up`` I could give some insights if you are interested.

For ``less falls``, judging from the code for the walking, I think https://github.com/HULKs/hulk/blob/main/crates/control/src/sole_pressure_filter.rs#L34 and https://github.com/HULKs/hulk/blob/main/crates/control/src/support_foot_estimation.rs#L52 could result in some problems, which _could_ explain a handful of falls at the last competition. With the low-pass filtering a detected support foot switch will be delayed. With the already present delay of about 3 motion frames between sending requests to the joints and the measured execution of such requests, adding more delay sounds like an unintended effect.

The usage of the hysterese, to decide which foot is the supporting one, is a good idea. But from lots of testing a hysterese should only be necessary if the FSRs of both feet measure close to 0 pressure. I am not sure, if this is only because we auto calibrate the FSRs values (similar to the original rUNSWift walk, but for both min and max values).

If both things are changed, I expect the actual walk duration to be closer to your intended 260 ms one (at the last RoboCup the robots looked like walking with a lot higher walk duration). From experience I can tell that this shorter duration is on average more stable, but _can_ result in other problems. Like worn out robots walking a lot slower than intended or your really strong forward kick resulting in a lot more falls. But those problems can be easily addressed.

**Comment by h3ndrk** [comment]
Moin @philipniklas-r, thank you very much for your input! We are currently looking into your proposed changes. :tada:
