### ISSUE TITLE
Only claim striker when seeing own ball

### ISSUE THREAD

**Issue by Narcha** [HULKs/hulk#484]
After reviewing footage from today's game vs. B-Human, @knoellle and I determined it is probably better to only claim the striker role when a robot has a lower time to reach kick position based on an own ball, not a team ball.
When receiving a team ball, robots should just search the area to confirm the detection, but delay claiming the striker role.

Summary of what went wrong:
- No. 1 was striker, with the ball right in front of it.
- No. 5 was standing right next to the ball, facing away.
- No. 5 received the ball location from No. 1
- Due to slight delocalization, No. 5 believed that the ball was right in front of it.
- No. 5 Claimed the striker role, causing No. 1 to back off unnecessarily.

This happened right around 5:26 left in the stream

Game controller screenshot:
![-5278250576557230916_121](https://github.com/HULKs/hulk/assets/42248344/0604aa46-6449-4b2e-8aa4-52715e761801)

YT stream screenshot:
![20230707_19h16m31s_grim](https://github.com/HULKs/hulk/assets/42248344/df54ec2e-d0d3-442b-b2c2-27169284c093)

**Comment by PasGl** [comment]
This change seems problematic to me.

In this particular situation it makes sense, but there are plenty of situations, specifically when the ball is close to the opponents goal, when a striker really should take action even if it is acting on a team-ball.

The problem here was a de-localization. Not the role-assignment decision. 

Changing the role-assignment decision to cover this case is a work-around that will have detrimental side-effects for other cases.

**Comment by schluis** [comment]
Based on @PasGl comment we don't want this.
