### ISSUE TITLE
No. 5 wrong spawn location on top of 3 (spawn hypothesis wrong)

### ISSUE THREAD

**Issue by Bendodroid** [HULKs/hulk#52]
Check spawn hypotheses for five robots in the SMD, at least one is wrong.

**Comment by knoellle** [comment]
Tested with five robots in the lab with the line detection fixes today, issue did not reoccur.
I checked the config files for spawn locations, in the default.json, the initial poses look correct and the smd location does not override them, nor do any of the hardware specific config files.
I'd guess there was some incorrectly associated line, but that should be fixed with #61 now.
