### ISSUE TITLE
Replay recording broken in webots

### ISSUE THREAD

**Issue by knoellle** [HULKs/hulk#581]
Replay recording tries to write files to `./logs/`, which by default doesn't exist in our repository.
This causes `pepsi run` to fail with weird error messages about closed channels, however, the actual error error message from the recording thread is not shown because the thread cleanup hangs on joining the audio cycler.

Workaround: create `logs` directory in working directory.

We should think about whether recording should be enabled by default at all for webots and if so, where/how long to store the logs.
I don't think unbounded logging by default is a good idea. On the nao, that's less of an issue since the log files are frequently removed by pepsi during our normal workflows.
However, that is not the case for local logfiles.

**Comment by h3ndrk** [comment]
- Disable all cyclers in `framework.json`
- By default enable in upload and pregame
- Only start recording writer thread and create files if at least one cycler is enabled

**Comment by h3ndrk** [comment]
Current idea:

- Two `framework.json` (NAO and Webots)
- Pepsi command allows to specify the target to control which file is mutated
- Recording thread runs all the time (because we will later allow to record single frames triggered via Communication, which requires a running thread)
- Recording thread will create files lazily at first write

**Comment by h3ndrk** [comment]
The directory is created by default, so should not be an issue anymore.
