### ISSUE TITLE
Fix hybrid alignment

### ISSUE THREAD

**Issue by schluis** [HULKs/hulk#643]
When we run to the kick-off position after scoring a goal, the striker seems to oscillate in the hybrid orientation when he reaches the end of his path. This means that he oscillates between turning left and right and sometimes never reaches the final kick-off position, resulting in an illegal position.

**Comment by knoellle** [comment]
Found the issue. We mistakenly assume that the robot orientation when entering the hybrid align area around the target is the direction from the current(!) position to the target.
We then slerp that orientation to the desired orientation. However, since we use the direction from the current position to the target, it can happen that the output of the slerp flips when rotating the other direction from the start would have been shorter.
This does not take into account the current orientation of the robot, causing it to turn the wrong way to catch up with the hybrid orientation interpolated the other way around.
